# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: 
  - oldrel
  - release
  - devel
cache: packages
bioc_packages: rhdf5
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
